# Generated by Django 3.1.5 on 2021-05-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteimg',
            name='file',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
